### ISSUE TITLE
Required Filetype 'PowerShell' is not compatible with parsing of the lsp (requires ps1 or psm1)

### ISSUE THREAD

**Issue by L4TDTBP** [Willem-J-an/nvim-dap-powershell#1]
Hello, thank you for this awesome plugin!

I kind of struggled with the filetypes. As soon as you override it with 'PowerShell' like it is mentioned in the docs, I lost the proper parsing of the code.

```lua
au BufRead,BufNewFile *.ps1 set filetype=PowerShell
au BufRead,BufNewFile *.psm1 set filetype=PowerShell
```

Adding PowerShell to the accepted filetypes in the LSP, does not help, sadly:

```lua
lspconfig.powershell_es.setup({
  filetypes = { "ps1","psm1","PowerShell" },
})
```

As soon as you change it back to ps1 --> :set filetype=ps1 - the parsing starts to work again, but you cannot start the debugger.

I figured out this workaround, but it would be nice if your plugin supports .ps1 and .psm1 as well.

```lua
dapPs.setup()
table.insert(dap.configurations.PowerShell, {
  type = "PowerShell",
 request = "launch",
  name = "My custom launch configuration",
  script = "${file}",
})
dap.configurations.ps1 = dap.configurations.PowerShell
dap.configurations.psm1 = dap.configurations.PowerShell
```

**Comment by Willem-J-an** [comment]
Thanks for the report, applying the configs to ps1 and psm1 seems like a nice solution. I implemented it, let me know if you have any other issues.
