### ISSUE TITLE
Debug doesn't seem to attach to anything

### ISSUE THREAD

**Issue by ryanwwhittaker** [Willem-J-an/nvim-dap-powershell#2]
This is probably something that I am doing or missing, rather than a real bug, but when I try to use this plugin I simply don't get any debugging happening at all.

Dapui shows the scope of a couple of breakpoints, but nothing else in console output or repl.
I believe Powershell Editor Services are running correctly as an LSOP as I get autocompletion etc.

This screenshot shows my dapui window on my very basic powershell hello.ps1 file.

![image](https://github.com/Willem-J-an/nvim-dap-powershell/assets/35874058/0606bec2-4d8e-4ded-a9e3-64bf85f7bd33)

I am running in Ubuntu 22.04.03 LTS on WSL2.

My simple plugin file is below:
return {
  {
    "mfussenegger/nvim-dap",
    dependencies = {
      "rcarriga/nvim-dap-ui",
      "Willem-J-an/nvim-dap-powershell",
      "nvim-lua/plenary.nvim",
      "mfussenegger/nvim-dap",
      "rcarriga/nvim-dap-ui",
      "nvim-neotest/nvim-nio",
      "m00qek/baleia.nvim",
    },

    config = function()
      local dap = require("dap")
      local dapui = require("dapui")

      require("dapui").setup()
      require("dap-powershell").setup()

      dap.listeners.after.event_initialized["dapui_config"] = function()
        dapui.open({})
        require("dap-powershell").correct_repl_colors()
      end
      vim.keymap.set("n", "<Leader>dt", dap.toggle_breakpoint, {})
      vim.keymap.set("n", "<F5>", dap.continue, {})
      vim.keymap.set("n", "<F10>", dap.step_over, {})
      vim.keymap.set("n", "<F11>", dap.step_into, {})
      vim.keymap.set("n", "<F12>", dap.step_out, {})
    end,
  },
}

**Comment by Willem-J-an** [comment]
LSP working is not necessarily indicative of working PSES, as dap server runs separate from lsp server. Would recommend to adjust the log level of nvim-dap and see if the logs tell you anything.

**Comment by ryanwwhittaker** [comment]
Setting the log level to trace seems to show that it is working - although I am not sure what I should expect here - it isn't showing any errors:
[ DEBUG ] 2024-05-27T07:30:16Z+0100 ] ...ryan/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1172 ]        "Starting debug adapter server executable"      {
  args = { "-NoLogo", "-NoProfile", "-NonInteractive", "-OutputFormat", "Text", "-File", "/home/ryan/.local/share/nvim/mason/packages/powershell-editor-services/PowerShellEditorServices/Start-EditorServices.ps1", "-BundledModulesPath", "/home/ryan/.local/share/nvim/mason/packages/powershell-editor-services", "-LogPath", "/tmp/lua_SwAXUod/logs.log", "-SessionDetailsPath", "/tmp/lua_SwAXUod/session.json", "-HostName", "Neovim", "-HostProfileId", "Neovim.DAP", "-HostVersion", "1.0.0", "-LogLevel", "Normal", "-DebugServiceOnly", "-DebugServicePipeName", "/tmp/lua_LF1E47" },
  command = "pwsh"
}
[ DEBUG ] 2024-05-27T07:30:16Z+0100 ] ...ryan/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1252 ]        "Debug adapter server executable started with pipe /tmp/lua_LF1E47"
[ DEBUG ] 2024-05-27T07:30:17Z+0100 ] ...ryan/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1700 ]        "request"       {
  arguments = {
    adapterID = "nvim-dap",
    clientID = "neovim",
    clientName = "neovim",
    columnsStartAt1 = true,
    linesStartAt1 = true,
    locale = "C.UTF-8",
    pathFormat = "path",
    supportsProgressReporting = true,
    supportsRunInTerminalRequest = true,
    supportsStartDebuggingRequest = true,
    supportsVariableType = true
  },
  command = "initialize",
  seq = 1,
  type = "request"
}
[ DEBUG ] 2024-05-27T07:30:17Z+0100 ] ...ryan/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:957 ] 1       {
  body = {
    supportsCancelRequest = true,
    supportsConditionalBreakpoints = true,
    supportsConfigurationDoneRequest = true,
    supportsFunctionBreakpoints = true,
    supportsHitConditionalBreakpoints = true,
    supportsLogPoints = true,
    supportsSetVariable = true
  },
  command = "initialize",
  request_seq = 1,
  seq = 1,
  success = true,
  type = "response"
}
[ DEBUG ] 2024-05-27T07:30:17Z+0100 ] ...ryan/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1700 ]        "request"       {
  arguments = {
    cwd = "/home/ryan/Repos/Test/hello.ps1",
    name = "PowerShell Launch Current File",
    program = "/home/ryan/Repos/Test/hello.ps1",
    request = "launch",
    type = "PowerShell"
  },
  command = "launch",
  seq = 2,
  type = "request"
}
[ DEBUG ] 2024-05-27T07:30:17Z+0100 ] ...ryan/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:957 ] 1       {
  body = vim.empty_dict(),
  command = "launch",
  request_seq = 2,
  seq = 2,
  success = true,
  type = "response"
}
[ DEBUG ] 2024-05-27T07:30:17Z+0100 ] ...ryan/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:957 ] 1       {
  body = vim.empty_dict(),
  event = "initialized",
  seq = 3,
  type = "event"
}
[ DEBUG ] 2024-05-27T07:30:17Z+0100 ] ...ryan/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1700 ]        "request"       {
  arguments = {
    breakpoints = { {
        line = 1
      } },
    lines = { 1 },
    source = {
      name = "hello.ps1",
      path = "/home/ryan/Repos/Test/hello.ps1"
    },
    sourceModified = false
  },
  command = "setBreakpoints",
  seq = 3,
  type = "request"
}
[ DEBUG ] 2024-05-27T07:30:17Z+0100 ] ...ryan/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:957 ] 1       {
  body = {
    breakpoints = { {
        id = 0,
        line = 1,
        source = {
          path = "/home/ryan/Repos/Test/hello.ps1"
        },
        verified = true
      } }
  },
  command = "setBreakpoints",
  request_seq = 3,
  seq = 4,
  success = true,
  type = "response"
}
[ DEBUG ] 2024-05-27T07:30:17Z+0100 ] ...ryan/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1700 ]        "request"       {
  command = "configurationDone",
  seq = 4,
  type = "request"
}
[ DEBUG ] 2024-05-27T07:30:17Z+0100 ] ...ryan/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:957 ] 1       {
  body = vim.empty_dict(),
  command = "configurationDone",
  request_seq = 4,
  seq = 5,
  success = true,
  type = "response"
}

**Comment by Willem-J-an** [comment]
Is your pses up to date?

**Comment by ryanwwhittaker** [comment]
I believe so - it is on 3.20.1

**Comment by Willem-J-an** [comment]
Ah, I see there was a bug in the plugin, I managed to reproduce and fix it. Please update the plugin and it should work now.

**Comment by ryanwwhittaker** [comment]
Fantastic - it works - I've been trying for over a week to get Powershell working in NeoVim.  You are a genius - thank you!
